name: Build Docker image

on:
  push:
    branches:
      - master
    tags:
      - .*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8.0'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: c2corg/serac-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
